apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init-db
data:
  init-database.sql: |
    CREATE DATABASE IF NOT EXISTS mydb;
    USE mydb;

    CREATE TABLE IF NOT EXISTS employees (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        department VARCHAR(100)
    );

