apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    name: frontend-service
    app: sirh-app
spec:
  selector:
    app: sirh-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002
  type: NodePort

