---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: sirh-app
    name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sirh-app
      name: frontend
  template:
    metadata:
      labels:
        app: sirh-app
        name: frontend
    spec:
      containers:
      - name: frontend
        image: omarstahii/frontend-service:2.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    name: frontend-service
    app: sirh-app
spec:
  selector:
    app: sirh-app
  ports:
    - port: 3000
      targetPort: 80
      nodePort: 30002
  type: NodePort
