---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: holidays-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sirh-app
      name: holidaysservice
  template:
    metadata:
      labels:
        app: sirh-app
        name: holidaysservice
    spec:
      containers:
        - name: holidays-service
          image: omarstahii/holidays-service:0.5
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mariadb://mariadb:3306/mydb?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: rootpassword

---
apiVersion: v1
kind: Service
metadata:
  name: holidaysservice-service
  labels:
    name: holidaysservice-service
    app: sirh-app
spec:
  selector:
    app: sirh-app
    name: holidaysservice
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP

