apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: localstack
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/instance: localstack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: localstack
    app.kubernetes.io/version: latest
    helm.sh/chart: localstack-0.6.16
  name: localstack-clusterip
  namespace: default
spec:
  type: NodePort  # Changed from ClusterIP to NodePort
  ports:
  - name: edge
    port: 4566
    protocol: TCP
    targetPort: 4566
    nodePort: 30003  # Optional, can be between 30000 and 32767. Kubernetes will assign if not specified.
  selector:
    app.kubernetes.io/instance: localstack
    app.kubernetes.io/name: localstack
  sessionAffinity: None
status:
  loadBalancer: {}

