apiVersion: v1
kind: Pod
metadata:
  name: mariadb-pod
  labels:
    name: mariadb-pod
    app: sirh-app
spec:
  containers:
    - name: mariadb
      image: mariadb:latest
      ports:
        - containerPort: 3306  # Default port for MariaDB is 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"    # Environment variable for the root password
        - name: MYSQL_USER
          value: "user"             # Environment variable to create a user
        - name: MYSQL_PASSWORD
          value: "password"         # Environment variable for the user's password
