apiVersion: v1
kind: Service
metadata:
  name: s3manager-service
  labels:
    name: s3manager-service
    app: sirh-app
spec:
  selector:
    app: sirh-app
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP

